apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo "Hello from PVC" > /data/hello.txt; sleep 3600']
      volumeMounts:
        - name: pvc-storage
          mountPath: /data           # The path inside the container
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: pvc-example       # The PVC this pod will use
