apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: busybox
    command: ['sh', '-c', 'mkdir /data; sleep 3600']
    volumeMounts:
     - mountPath: /data #path on the container
       name: hpvolume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: hpvolume
      hostPath:
        path: / # path on cluster