apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels:
    name: nginx-nodePort
spec:
  type: NodePort
  selector: 
    app: nginx
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001 